---
- name: Pull Docker Image of Calculator
  hosts: localhost
#  vars:
#    ansible_python_interpreter: /usr/bin/pyt3
  tasks:
    - name: Pull image
      docker_image:
        name: 48483/calculatorelk:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Calculator 48483/calculatorelk
